### ISSUE TITLE
InvalidOperationException: This operation is only valid on generic types.

### ISSUE THREAD

**Issue by moar** [edandersen/core-admin#77]
Hello,

I get this error when trying to Edit a user, which inherits from IdentityUser. This is the error I get:

System.InvalidOperationException: This operation is only valid on generic types.
   at System.RuntimeType.GetGenericTypeDefinition()
   at DotNetEd.CoreAdmin.Controllers.CoreAdminDataController.<>c__DisplayClass3_1.<GetDbSetValueOrNull>b__1(PropertyInfo p)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at DotNetEd.CoreAdmin.Controllers.CoreAdminDataController.GetDbSetValueOrNull(String dbSetName, DbContext& dbContextObject, Type& typeOfEntity, Dictionary`2& relationships)
   at DotNetEd.CoreAdmin.Controllers.CoreAdminDataController.GetEntityFromDbSet(String dbSetName, String id, DbContext& dbContextObject, Type& typeOfEntity, Dictionary`2& relationships)
   at DotNetEd.CoreAdmin.Controllers.CoreAdminDataController.EditEntity(String dbSetName, String id)
   at lambda_method245(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by AbdoMahfoz** [comment]
This happens when there are properties in your `DbContext` that are not of type `DbSet` that are written above your `DbSet` properties
The solution is simple, make sure all `DbSet` properties are above all other properties!

Why this happens? because of this line in `CoreAdminDataController.cs`, line 96-98
```cs
 var targetChildListOnDbContext = dbContextObject.GetType().GetProperties()
                                    .FirstOrDefault(p => p.PropertyType.GetGenericTypeDefinition() == typeof(DbSet<>)
                                    && p.PropertyType.GetGenericArguments().First().FullName == typeOfChild.PrincipalEntityType.Name);
```
Specifically, calling `p.PropertyType.GetGenericTypeDefinition()` as you iterate through all `DbContext` properties

I will fix it in a PR if @edandersen doesn't mind <3

**Comment by edandersen** [comment]
Brilliant! Go nuts pal :-)

________________________________
