### ISSUE TITLE
System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.

### ISSUE THREAD

**Issue by Dredy** [edandersen/core-admin#83]
Trying to view a table with many NULL fields (Allow nulls checked in table designer) i receive the following error

System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
 at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
         at Microsoft.Data.SqlClient.SqlBuffer.get_String()
         at Microsoft.Data.SqlClient.SqlDataReader.GetString(Int32 i)
         at lambda_method84(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
         at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
         at AspNetCoreGeneratedDocument.Views_Shared_MvcGrid__Grid.ExecuteAsync()
         
it seems that MvcGrid tries to get a value from a null field.

There is any suggestino to avoid this problem?

Thank You.

**Comment by Dredy** [comment]
I solved the issue by myself.
#nullable disable
on top of the model class
